server:
  port: 8081

spring:
  application:
    name: BOOKING-SERVICE
  docker:
    compose:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true
