server:
  port: 8080

spring:
  application:
    name: travel-api-gateway

  data:
    redis:
      host: redis
      port: 6379
      name: redis-cache

  cloud:
    discovery:
      enabled: true

    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 5   # peticiones por segundo
            redis-rate-limiter.burstCapacity: 10
            key-resolver: "#{@apiKeyResolver}"    # resolver por API key

      routes:
        # Ruta Itinerary Service
        - id: itinerary-service
          uri: lb://ITINERARY-SERVICE
          predicates:
            - Path=/api/public/itinerary/**
          filters:
            # Reescribe la URL pública a la interna
            - RewritePath=/api/public/itinerary/(?<segment>.*), /api/itinerary/v1/${segment}
            # Circuit breaker con fallback
            - name: CircuitBreaker
              args:
                name: itineraryCB
                fallbackUri: forward:/fallback/itinerary

        # Ruta Booking Service
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/public/booking/**
          filters:
            # Reescribe la URL pública a la interna
            - RewritePath=/api/public/booking/(?<segment>.*), /api/booking/v1/${segment}
            # Circuit breaker con fallback
            - name: CircuitBreaker
              args:
                name: bookingCB
                fallbackUri: forward:/fallback/booking

resilience4j:
  circuitbreaker:
    instances:
      itineraryCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      bookingCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true
