server:
  port: 8082

spring:
  application:
    name: ITINERARY-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true
